### ISSUE TITLE
Running a Create Block Theme export on a fresh clone changes theme.json

### ISSUE THREAD

**Issue by itsamoreh** [WebDevStudios/wds-bt#29]
[Create Block Theme's export feature](https://github.com/WordPress/create-block-theme?tab=readme-ov-file#1-export) is a great way to get changes to theme.json, templates, template parts, etc... into the file system where they can then be committed to the repo.

However, when running a Create Block Theme export on a freshly cloned copy of wds-bt, I see a lot of changes. It looks like the vast majority of the changes are just moving things around in `theme.json`.

Should we run a Create Block Theme export and commit the changes to wds-bt?

see https://github.com/WebDevStudios/wds-bt/pull/24/files for the changes to `theme.json`

**Comment by lswilson** [comment]
Thanks @itsamoreh ! Adding @johnheimkes to this for visibility - he's working on version control for this.

**Comment by itsamoreh** [comment]
Fixed via https://github.com/WebDevStudios/wds-bt/pull/47
