### ISSUE TITLE
Hook to remove the archive title prefix breaks the "Show archive type in title" feature in core/query-title

### ISSUE THREAD

**Issue by itsamoreh** [WebDevStudios/wds-bt#30]
Should we remove this `remove-archive-title-prefix.php` hook? The `core/query-title` block has an option to remove the prefix which doesn't have any affect since we're always removing the prefix via a hook in the theme.

![image](https://github.com/WebDevStudios/wds-bt/assets/12365909/fe055eeb-bdab-4e7c-8c1e-6f20b09a24f1)

See https://wordpress.org/documentation/article/archive-title-block/#block-settings

The hook in wds-bt:
https://github.com/WebDevStudios/wds-bt/blob/c5d404f73ac1821b616c90a48d470b549e48abf1/inc/hooks/remove-archive-title-prefix.php#L1-L30

**Comment by khleomix** [comment]
Thanks @itsamoreh. This will be removed in the next release. Closing as done.
