### ISSUE TITLE
Does enable-svg open a gate to XSS?

### ISSUE THREAD

**Issue by martinpl** [WebDevStudios/wds-bt#42]
Hello,
Browsing the code i notice that code [enable-svg.php](https://github.com/WebDevStudios/wds-bt/blob/main/inc/hooks/enable-svg.php), and i'm wondering, if this is secure i'm guessing that SVG plugins do some additional checks for script content.

**Comment by itsamoreh** [comment]
Thanks @martinpl! We've removed this file from the theme.
